[changelog]
header = ""
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}]
{% else %}## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
{%- set message = commit.message %}
{%- if commit.remote.pr_number %}
{%- set message = message | trim_end_matches(pat=" (#" ~ commit.remote.pr_number ~ ")") %}
{%- endif %}
- {% if commit.breaking %}**Breaking:** {% endif %}{% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ message }} {% if commit.remote.pr_number %}([#{{ commit.remote.pr_number }}](https://github.com/azohra/yaml.sh/pull/{{ commit.remote.pr_number }})){% else %}([{{ commit.id | truncate(length=7, end="") }}](https://github.com/azohra/yaml.sh/commit/{{ commit.id }})){% endif %}
{% if commit.breaking_description %}
  **Breaking change:** {{ commit.breaking_description | indent(prefix="  ", first=false) }}
{% endif %}{% endfor %}{% endfor %}
{% if version %}
[{{ version | trim_start_matches(pat="v") }}]: https://github.com/azohra/yaml.sh/compare/{{ previous.version }}...{{ version }}
{% endif %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
tag_pattern = '^v[0-9]+\.[0-9]+\.[0-9]+$'
use_branch_tags = true
sort_commits = "oldest"
commit_parsers = [
  { message = '^feat', group = "Added" },
  { message = '^fix', group = "Fixed" },
  { message = '^perf', group = "Performance" },
  { message = '^docs', group = "Documentation" },
  { message = '.*', group = "Other changes" },
]

[remote.github]
owner = "azohra"
repo = "yaml.sh"
