#!/bin/sh

: "${YSH_REAL_AWK:?YSH_REAL_AWK is required}"
YSH_AWK_BINARY=$YSH_REAL_AWK

if [ ! -x "$YSH_AWK_BINARY" ]; then
    printf '%s\n' 'fault wrapper could not find the real awk' >&2
    exit 127
fi

if [ -n "${YSH_AWK_MUTATE_FILE:-}" ]; then
    printf '%s\n' "${YSH_AWK_MUTATE_CONTENT:-externally changed}" > "$YSH_AWK_MUTATE_FILE"
fi

exec "$YSH_AWK_BINARY" "$@"
