name: Conventional PR

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions: {}

jobs:
  title:
    name: Conventional PR title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: azohra/conventional-pr@c86109511263ca80e66a2fb8500182c2890dc121
