name: Conventional PR

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  title:
    uses: azohra/.github/.github/workflows/title.yml@main
